# Site Settings
title: Bare Neural Net
description: Breaking the Black Box of ML with Rust

# Markdown & Math
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Exclude files from being built into the site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor