title: Build Neural Network From Scratch in Rust
markdown: kramdown
highlighter: rouge

author_name: "Palash Kanti Kundu"
author_bio: "14-year SE veteran specialized in Java, Rust, and System Design; I build everything from ML libraries to distributed systems and guitalele tutorials."
github_username: "palash90"
linkedin_username: "palash90"
devto_username: "palash90"